{"uid":"555d109e6e4def26","name":"Exception test","fullName":"tests.forgot_password_test.TestForgotPassword#test_expected_exception_on_page_title","historyId":"288cd0030c92ba34b4ff4b58ed8ec476","time":{"start":1713150043884,"stop":1713150054149,"duration":10265},"description":"Exception catching","descriptionHtml":"<p>Exception catching</p>\n","status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x55889a012873 <unknown>\n#1 0x558899d088c6 <unknown>\n#2 0x558899d53618 <unknown>\n#3 0x558899d536d1 <unknown>\n#4 0x558899d96744 <unknown>\n#5 0x558899d755cd <unknown>\n#6 0x558899d93c19 <unknown>\n#7 0x558899d75343 <unknown>\n#8 0x558899d46593 <unknown>\n#9 0x558899d46f5e <unknown>\n#10 0x558899fd685b <unknown>\n#11 0x558899fda7b5 <unknown>\n#12 0x558899fc4581 <unknown>\n#13 0x558899fdb342 <unknown>\n#14 0x558899fa988f <unknown>\n#15 0x55889a001738 <unknown>\n#16 0x55889a00190b <unknown>\n#17 0x55889a0119c4 <unknown>\n#18 0x7fda51294ac3 <unknown>","statusTrace":"self = <tests.forgot_password_test.TestForgotPassword object at 0x7f5b145df7a0>\n\n    @allure.description(\"Exception catching\")\n    @allure.title(\"Exception test\")\n    @allure.link(\"github.com/allure-examples/\", name=\"Allure Examples\")\n    @allure.issue(\"github.com/allure-examples/allure-examples/issues/1\", name=\"ISSUE-1\")\n    @allure.testcase(\n        \"github.com/allure-examples/allure-examples/issues/2\", name=\"TESTCASE-2\"\n    )\n    def test_expected_exception_on_page_title(self):\n>       self.about_page.click_login_link()\n\ntests/forgot_password_test.py:53: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/about_page.py:20: in click_login_link\n    self.click(self.LOGIN_LINK)\npages/base_page.py:60: in click\n    el: WebElement = self.wait.until(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"5d91dc0f7a89713cf95fb987746943b4\")>\nmethod = <function element_to_be_clickable.<locals>._predicate at 0x7f5b144ceb60>\nmessage = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       #0 0x55889a012873 <unknown>\nE       #1 0x558899d088c6 <unknown>\nE       #2 0x558899d53618 <unknown>\nE       #3 0x558899d536d1 <unknown>\nE       #4 0x558899d96744 <unknown>\nE       #5 0x558899d755cd <unknown>\nE       #6 0x558899d93c19 <unknown>\nE       #7 0x558899d75343 <unknown>\nE       #8 0x558899d46593 <unknown>\nE       #9 0x558899d46f5e <unknown>\nE       #10 0x558899fd685b <unknown>\nE       #11 0x558899fda7b5 <unknown>\nE       #12 0x558899fc4581 <unknown>\nE       #13 0x558899fdb342 <unknown>\nE       #14 0x558899fa988f <unknown>\nE       #15 0x55889a001738 <unknown>\nE       #16 0x55889a00190b <unknown>\nE       #17 0x55889a0119c4 <unknown>\nE       #18 0x7fda51294ac3 <unknown>\n\n.venv/lib/python3.12/site-packages/selenium/webdriver/support/wait.py:105: TimeoutException","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"base_url","time":{"start":1713149845499,"stop":1713149845499,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"_verify_url","time":{"start":1713149845499,"stop":1713149845499,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"session_request","time":{"start":1713149845499,"stop":1713149845499,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"description":"Exception catching","status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x55889a012873 <unknown>\n#1 0x558899d088c6 <unknown>\n#2 0x558899d53618 <unknown>\n#3 0x558899d536d1 <unknown>\n#4 0x558899d96744 <unknown>\n#5 0x558899d755cd <unknown>\n#6 0x558899d93c19 <unknown>\n#7 0x558899d75343 <unknown>\n#8 0x558899d46593 <unknown>\n#9 0x558899d46f5e <unknown>\n#10 0x558899fd685b <unknown>\n#11 0x558899fda7b5 <unknown>\n#12 0x558899fc4581 <unknown>\n#13 0x558899fdb342 <unknown>\n#14 0x558899fa988f <unknown>\n#15 0x55889a001738 <unknown>\n#16 0x55889a00190b <unknown>\n#17 0x55889a0119c4 <unknown>\n#18 0x7fda51294ac3 <unknown>","statusTrace":"self = <tests.forgot_password_test.TestForgotPassword object at 0x7f5b145df7a0>\n\n    @allure.description(\"Exception catching\")\n    @allure.title(\"Exception test\")\n    @allure.link(\"github.com/allure-examples/\", name=\"Allure Examples\")\n    @allure.issue(\"github.com/allure-examples/allure-examples/issues/1\", name=\"ISSUE-1\")\n    @allure.testcase(\n        \"github.com/allure-examples/allure-examples/issues/2\", name=\"TESTCASE-2\"\n    )\n    def test_expected_exception_on_page_title(self):\n>       self.about_page.click_login_link()\n\ntests/forgot_password_test.py:53: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/about_page.py:20: in click_login_link\n    self.click(self.LOGIN_LINK)\npages/base_page.py:60: in click\n    el: WebElement = self.wait.until(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"5d91dc0f7a89713cf95fb987746943b4\")>\nmethod = <function element_to_be_clickable.<locals>._predicate at 0x7f5b144ceb60>\nmessage = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       #0 0x55889a012873 <unknown>\nE       #1 0x558899d088c6 <unknown>\nE       #2 0x558899d53618 <unknown>\nE       #3 0x558899d536d1 <unknown>\nE       #4 0x558899d96744 <unknown>\nE       #5 0x558899d755cd <unknown>\nE       #6 0x558899d93c19 <unknown>\nE       #7 0x558899d75343 <unknown>\nE       #8 0x558899d46593 <unknown>\nE       #9 0x558899d46f5e <unknown>\nE       #10 0x558899fd685b <unknown>\nE       #11 0x558899fda7b5 <unknown>\nE       #12 0x558899fc4581 <unknown>\nE       #13 0x558899fdb342 <unknown>\nE       #14 0x558899fa988f <unknown>\nE       #15 0x55889a001738 <unknown>\nE       #16 0x55889a00190b <unknown>\nE       #17 0x55889a0119c4 <unknown>\nE       #18 0x7fda51294ac3 <unknown>\n\n.venv/lib/python3.12/site-packages/selenium/webdriver/support/wait.py:105: TimeoutException","steps":[{"name":"Click Login link","time":{"start":1713150043885,"stop":1713150054149,"duration":10264},"status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x55889a012873 <unknown>\n#1 0x558899d088c6 <unknown>\n#2 0x558899d53618 <unknown>\n#3 0x558899d536d1 <unknown>\n#4 0x558899d96744 <unknown>\n#5 0x558899d755cd <unknown>\n#6 0x558899d93c19 <unknown>\n#7 0x558899d75343 <unknown>\n#8 0x558899d46593 <unknown>\n#9 0x558899d46f5e <unknown>\n#10 0x558899fd685b <unknown>\n#11 0x558899fda7b5 <unknown>\n#12 0x558899fc4581 <unknown>\n#13 0x558899fdb342 <unknown>\n#14 0x558899fa988f <unknown>\n#15 0x55889a001738 <unknown>\n#16 0x55889a00190b <unknown>\n#17 0x55889a0119c4 <unknown>\n#18 0x7fda51294ac3 <unknown>\n\n","statusTrace":"  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/.venv/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/pages/about_page.py\", line 20, in click_login_link\n    self.click(self.LOGIN_LINK)\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/pages/base_page.py\", line 60, in click\n    el: WebElement = self.wait.until(\n                     ^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/.venv/lib/python3.12/site-packages/selenium/webdriver/support/wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},{"name":"public ip address","time":{"start":1713150054158,"stop":1713150054305,"duration":147},"status":"passed","steps":[],"attachments":[{"uid":"b8692b576363b3bf","name":"HTTP logs of http://checkip.amazonaws.com/","source":"b8692b576363b3bf.txt","type":"text/plain","size":260}],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false}],"attachments":[{"uid":"2cbb980ca9e30d68","name":"Cookies","source":"2cbb980ca9e30d68.json","type":"application/json","size":3578},{"uid":"282ae45bb5069147","name":"Session Storage","source":"282ae45bb5069147.json","type":"application/json","size":358},{"uid":"bbee320eaf2d9889","name":"Local Storage","source":"bbee320eaf2d9889.json","type":"application/json","size":350},{"uid":"41e89eccdbedc0cf","name":"Console Logs","source":"41e89eccdbedc0cf.json","type":"application/json","size":7723},{"uid":"b8406fe583f49e3c","name":"Full Page Screenshot","source":"b8406fe583f49e3c.png","type":"image/png","size":6240362},{"uid":"40f8208f8ab5a6d2","name":"URL","source":"40f8208f8ab5a6d2.uri","type":"text/uri-list","size":23},{"uid":"8eab200a65ac63dd","name":"Network Logs","source":"8eab200a65ac63dd.json","type":"application/json","size":40392}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":2,"attachmentsCount":8,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"session_request::0","time":{"start":1713150108808,"stop":1713150108808,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"suite","value":"Custom suite"},{"name":"subSuite","value":"Custom sub suite"},{"name":"severity","value":"critical"},{"name":"epic","value":"Security"},{"name":"story","value":"Forgot Password Feature's Functionality"},{"name":"parentSuite","value":"Custom parent suite"},{"name":"tag","value":"security"},{"name":"host","value":"fv-az1148-349"},{"name":"thread","value":"2383-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.forgot_password_test"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[{"name":"TESTCASE-2","url":"https://github.com/allure-examples/allure-examples/issues/2","type":"tms"},{"name":"ISSUE-1","url":"https://github.com/allure-examples/allure-examples/issues/1","type":"issue"},{"name":"Allure Examples","url":"https://github.com/allure-examples/","type":"link"}],"hidden":false,"retry":false,"extra":{"severity":"critical","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":["security"]},"source":"555d109e6e4def26.json","parameterValues":[]}