{"uid":"4eee7803c0776893","name":"Create new workspace test","fullName":"tests.workspaces_test.TestWorkspaces#test_create_new_workspace","historyId":"e1f088bc30a040de4100d958931562b3","time":{"start":1751939846557,"stop":1751939846557,"duration":0},"description":"Create new Workspace","descriptionHtml":"<p>Create new Workspace</p>\n","status":"broken","statusMessage":"FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/src/resources/tests_data.json'","statusTrace":"@fixture(scope=\"session\")\n    def data() -> Data:\n        json_path = Constants.DATA_PATH / \"tests_data.json\"\n>       with open(json_path, encoding=\"utf-8\") as json_file:\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE       FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/src/resources/tests_data.json'\n\ntests/conftest.py:60: FileNotFoundError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"base_url","time":{"start":1751939863379,"stop":1751939863379,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"_verify_url","time":{"start":1751939863379,"stop":1751939863379,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"session_request","time":{"start":1751939863379,"stop":1751939863379,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"data","time":{"start":1751939863380,"stop":1751939863380,"duration":0},"status":"broken","statusMessage":"FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/src/resources/tests_data.json'\n","statusTrace":"  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/.venv/lib/python3.13/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 929, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/tests/conftest.py\", line 60, in data\n    with open(json_path, encoding=\"utf-8\") as json_file:\n         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},{"name":"setup_method_fixture","time":{"start":1751939885446,"stop":1751939895818,"duration":10372},"status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x55cfc17ec53a <unknown>\n#1 0x55cfc12e7f00 <unknown>\n#2 0x55cfc1337c0c <unknown>\n#3 0x55cfc1337e31 <unknown>\n#4 0x55cfc137dbd4 <unknown>\n#5 0x55cfc135c5cd <unknown>\n#6 0x55cfc137af84 <unknown>\n#7 0x55cfc135c343 <unknown>\n#8 0x55cfc132978a <unknown>\n#9 0x55cfc132a9de <unknown>\n#10 0x55cfc17b62cb <unknown>\n#11 0x55cfc17ba242 <unknown>\n#12 0x55cfc17a37ac <unknown>\n#13 0x55cfc17badf7 <unknown>\n#14 0x55cfc1787b2f <unknown>\n#15 0x55cfc17db1a8 <unknown>\n#16 0x55cfc17db370 <unknown>\n#17 0x55cfc17eb3b6 <unknown>\n#18 0x7f44df09caa4 <unknown>\n#19 0x7f44df129c3c <unknown>\n\n","statusTrace":"  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/.venv/lib/python3.13/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 929, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/tests/workspaces_test.py\", line 25, in setup_method_fixture\n    login(self.about_page, self.login_page)\n    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/tests/workspaces_test.py\", line 15, in login\n    about_page.click_login_link()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/.venv/lib/python3.13/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/src/pages/about_page.py\", line 18, in click_login_link\n    self.click(self.LOGIN_LINK)\n    ~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/src/pages/base_page.py\", line 59, in click\n    el: WebElement = self.wait.until(expected_conditions.element_to_be_clickable(locator))\n                     ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/.venv/lib/python3.13/site-packages/selenium/webdriver/support/wait.py\", line 138, in until\n    raise TimeoutException(message, screen, stacktrace)\n","steps":[{"name":"Click Login link","time":{"start":1751939885446,"stop":1751939895817,"duration":10371},"status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x55cfc17ec53a <unknown>\n#1 0x55cfc12e7f00 <unknown>\n#2 0x55cfc1337c0c <unknown>\n#3 0x55cfc1337e31 <unknown>\n#4 0x55cfc137dbd4 <unknown>\n#5 0x55cfc135c5cd <unknown>\n#6 0x55cfc137af84 <unknown>\n#7 0x55cfc135c343 <unknown>\n#8 0x55cfc132978a <unknown>\n#9 0x55cfc132a9de <unknown>\n#10 0x55cfc17b62cb <unknown>\n#11 0x55cfc17ba242 <unknown>\n#12 0x55cfc17a37ac <unknown>\n#13 0x55cfc17badf7 <unknown>\n#14 0x55cfc1787b2f <unknown>\n#15 0x55cfc17db1a8 <unknown>\n#16 0x55cfc17db370 <unknown>\n#17 0x55cfc17eb3b6 <unknown>\n#18 0x7f44df09caa4 <unknown>\n#19 0x7f44df129c3c <unknown>\n\n","statusTrace":"  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/.venv/lib/python3.13/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/src/pages/about_page.py\", line 18, in click_login_link\n    self.click(self.LOGIN_LINK)\n    ~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/src/pages/base_page.py\", line 59, in click\n    el: WebElement = self.wait.until(expected_conditions.element_to_be_clickable(locator))\n                     ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/.venv/lib/python3.13/site-packages/selenium/webdriver/support/wait.py\", line 138, in until\n    raise TimeoutException(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":1,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"testStage":{"description":"Create new Workspace","status":"broken","statusMessage":"FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/src/resources/tests_data.json'","statusTrace":"@fixture(scope=\"session\")\n    def data() -> Data:\n        json_path = Constants.DATA_PATH / \"tests_data.json\"\n>       with open(json_path, encoding=\"utf-8\") as json_file:\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE       FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/src/resources/tests_data.json'\n\ntests/conftest.py:60: FileNotFoundError","steps":[{"name":"public ip address","time":{"start":1751939863428,"stop":1751939863587,"duration":159},"status":"passed","steps":[],"attachments":[{"uid":"f0c751fcfb18d436","name":"HTTP logs of http://checkip.amazonaws.com/","source":"f0c751fcfb18d436.txt","type":"text/plain","size":358}],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false}],"attachments":[{"uid":"bfba4795f01b05ae","name":"Cookies","source":"bfba4795f01b05ae.json","type":"application/json","size":4116},{"uid":"2f797420f86505a9","name":"Session Storage","source":"2f797420f86505a9.json","type":"application/json","size":359},{"uid":"1a4d88e861f5d420","name":"Local Storage","source":"1a4d88e861f5d420.json","type":"application/json","size":548},{"uid":"269f43f431a0d660","name":"Full Page Screenshot","source":"269f43f431a0d660.png","type":"image/png","size":1862269},{"uid":"6adeec8fe91104a0","name":"URL","source":"6adeec8fe91104a0.uri","type":"text/uri-list","size":23},{"uid":"6f06bfcde4ef58f4","name":"Network Logs","source":"6f06bfcde4ef58f4.json","type":"application/json","size":7932717}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":1,"attachmentsCount":7,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"session_request::0","time":{"start":1751939941055,"stop":1751939941055,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"epic","value":"Workspaces"},{"name":"severity","value":"normal"},{"name":"story","value":"WorkSpaces Creation and Editing Functionality"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"workspaces_test"},{"name":"subSuite","value":"TestWorkspaces"},{"name":"host","value":"fv-az1280-891"},{"name":"thread","value":"2101-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.workspaces_test"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":8,"skipped":0,"passed":0,"unknown":0,"total":8},"items":[{"uid":"cf2f020cfadad28a","reportUrl":"https://nirtal85.github.io/Selenium-Python-Example/707//#testresult/cf2f020cfadad28a","status":"broken","statusDetails":"FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/src/resources/tests_data.json'","time":{"start":1751853744409,"stop":1751853744409,"duration":0}},{"uid":"6411b20ef1f0b203","reportUrl":"https://nirtal85.github.io/Selenium-Python-Example/706//#testresult/6411b20ef1f0b203","status":"broken","statusDetails":"FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/src/resources/tests_data.json'","time":{"start":1751767526081,"stop":1751767526081,"duration":0}},{"uid":"2f0d02c25228e0b0","reportUrl":"https://nirtal85.github.io/Selenium-Python-Example/705//#testresult/2f0d02c25228e0b0","status":"broken","statusDetails":"FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/src/resources/tests_data.json'","time":{"start":1751680333097,"stop":1751680333097,"duration":0}},{"uid":"27f5868c3a7e2222","reportUrl":"https://nirtal85.github.io/Selenium-Python-Example/704//#testresult/27f5868c3a7e2222","status":"broken","statusDetails":"FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/src/resources/tests_data.json'","time":{"start":1751594171893,"stop":1751594171893,"duration":0}},{"uid":"be2f50f7c718e51f","reportUrl":"https://nirtal85.github.io/Selenium-Python-Example/703//#testresult/be2f50f7c718e51f","status":"broken","statusDetails":"FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/src/resources/tests_data.json'","time":{"start":1751507802997,"stop":1751507802997,"duration":0}},{"uid":"3ae89a64cf17ae58","reportUrl":"https://nirtal85.github.io/Selenium-Python-Example/702//#testresult/3ae89a64cf17ae58","status":"broken","statusDetails":"FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/src/resources/tests_data.json'","time":{"start":1751421381132,"stop":1751421381132,"duration":0}},{"uid":"4c59a8124119d807","reportUrl":"https://nirtal85.github.io/Selenium-Python-Example/701//#testresult/4c59a8124119d807","status":"broken","statusDetails":"FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/src/resources/tests_data.json'","time":{"start":1751335663406,"stop":1751335663406,"duration":0}}]},"tags":[]},"source":"4eee7803c0776893.json","parameterValues":[]}