{"uid":"17e0830812a5235d","name":"Create new workspace test","fullName":"tests.workspaces_test.TestWorkspaces#test_create_new_workspace","historyId":"e1f088bc30a040de4100d958931562b3","time":{"start":1749520586632,"stop":1749520586632,"duration":0},"description":"Create new Workspace","descriptionHtml":"<p>Create new Workspace</p>\n","status":"broken","statusMessage":"FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/src/resources/tests_data.json'","statusTrace":"@fixture(scope=\"session\")\n    def data() -> Data:\n        json_path = Constants.DATA_PATH / \"tests_data.json\"\n>       with open(json_path, encoding=\"utf-8\") as json_file:\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE       FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/src/resources/tests_data.json'\n\ntests/conftest.py:60: FileNotFoundError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_verify_url","time":{"start":1749520597433,"stop":1749520597433,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"base_url","time":{"start":1749520597433,"stop":1749520597433,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"data","time":{"start":1749520597434,"stop":1749520597434,"duration":0},"status":"broken","statusMessage":"FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/src/resources/tests_data.json'\n","statusTrace":"  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/.venv/lib/python3.13/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 929, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/tests/conftest.py\", line 60, in data\n    with open(json_path, encoding=\"utf-8\") as json_file:\n         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},{"name":"session_request","time":{"start":1749520597434,"stop":1749520597434,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"setup_method_fixture","time":{"start":1749520614233,"stop":1749520624289,"duration":10056},"status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x563c49a2753a <unknown>\n#1 0x563c49522f00 <unknown>\n#2 0x563c49572c0c <unknown>\n#3 0x563c49572e31 <unknown>\n#4 0x563c495b8bd4 <unknown>\n#5 0x563c495975cd <unknown>\n#6 0x563c495b5f84 <unknown>\n#7 0x563c49597343 <unknown>\n#8 0x563c4956478a <unknown>\n#9 0x563c495659de <unknown>\n#10 0x563c499f12cb <unknown>\n#11 0x563c499f5242 <unknown>\n#12 0x563c499de7ac <unknown>\n#13 0x563c499f5df7 <unknown>\n#14 0x563c499c2b2f <unknown>\n#15 0x563c49a161a8 <unknown>\n#16 0x563c49a16370 <unknown>\n#17 0x563c49a263b6 <unknown>\n#18 0x7f42c9a9caa4 <unknown>\n#19 0x7f42c9b29c3c <unknown>\n\n","statusTrace":"  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/.venv/lib/python3.13/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 929, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/tests/workspaces_test.py\", line 25, in setup_method_fixture\n    login(self.about_page, self.login_page)\n    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/tests/workspaces_test.py\", line 15, in login\n    about_page.click_login_link()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/.venv/lib/python3.13/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/src/pages/about_page.py\", line 18, in click_login_link\n    self.click(self.LOGIN_LINK)\n    ~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/src/pages/base_page.py\", line 59, in click\n    el: WebElement = self.wait.until(expected_conditions.element_to_be_clickable(locator))\n                     ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/.venv/lib/python3.13/site-packages/selenium/webdriver/support/wait.py\", line 138, in until\n    raise TimeoutException(message, screen, stacktrace)\n","steps":[{"name":"Click Login link","time":{"start":1749520614233,"stop":1749520624288,"duration":10055},"status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x563c49a2753a <unknown>\n#1 0x563c49522f00 <unknown>\n#2 0x563c49572c0c <unknown>\n#3 0x563c49572e31 <unknown>\n#4 0x563c495b8bd4 <unknown>\n#5 0x563c495975cd <unknown>\n#6 0x563c495b5f84 <unknown>\n#7 0x563c49597343 <unknown>\n#8 0x563c4956478a <unknown>\n#9 0x563c495659de <unknown>\n#10 0x563c499f12cb <unknown>\n#11 0x563c499f5242 <unknown>\n#12 0x563c499de7ac <unknown>\n#13 0x563c499f5df7 <unknown>\n#14 0x563c499c2b2f <unknown>\n#15 0x563c49a161a8 <unknown>\n#16 0x563c49a16370 <unknown>\n#17 0x563c49a263b6 <unknown>\n#18 0x7f42c9a9caa4 <unknown>\n#19 0x7f42c9b29c3c <unknown>\n\n","statusTrace":"  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/.venv/lib/python3.13/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/src/pages/about_page.py\", line 18, in click_login_link\n    self.click(self.LOGIN_LINK)\n    ~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/src/pages/base_page.py\", line 59, in click\n    el: WebElement = self.wait.until(expected_conditions.element_to_be_clickable(locator))\n                     ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/.venv/lib/python3.13/site-packages/selenium/webdriver/support/wait.py\", line 138, in until\n    raise TimeoutException(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":1,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"testStage":{"description":"Create new Workspace","status":"broken","statusMessage":"FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/src/resources/tests_data.json'","statusTrace":"@fixture(scope=\"session\")\n    def data() -> Data:\n        json_path = Constants.DATA_PATH / \"tests_data.json\"\n>       with open(json_path, encoding=\"utf-8\") as json_file:\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE       FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/src/resources/tests_data.json'\n\ntests/conftest.py:60: FileNotFoundError","steps":[{"name":"public ip address","time":{"start":1749520597610,"stop":1749520597732,"duration":122},"status":"passed","steps":[],"attachments":[{"uid":"682a9f41cb90aec7","name":"HTTP logs of http://checkip.amazonaws.com/","source":"682a9f41cb90aec7.txt","type":"text/plain","size":358}],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false}],"attachments":[{"uid":"d27f7bd07e56e613","name":"Cookies","source":"d27f7bd07e56e613.json","type":"application/json","size":4117},{"uid":"88d758480ac05707","name":"Session Storage","source":"88d758480ac05707.json","type":"application/json","size":359},{"uid":"5294336a6eafb894","name":"Local Storage","source":"5294336a6eafb894.json","type":"application/json","size":548},{"uid":"830762266d15456c","name":"Full Page Screenshot","source":"830762266d15456c.png","type":"image/png","size":1364194},{"uid":"140601773d53984","name":"URL","source":"140601773d53984.uri","type":"text/uri-list","size":23},{"uid":"b76358162f43a5e8","name":"Network Logs","source":"b76358162f43a5e8.json","type":"application/json","size":48957}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":1,"attachmentsCount":7,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"session_request::0","time":{"start":1749520661600,"stop":1749520661600,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"story","value":"WorkSpaces Creation and Editing Functionality"},{"name":"epic","value":"Workspaces"},{"name":"severity","value":"normal"},{"name":"tag","value":"run(order=1)"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"workspaces_test"},{"name":"subSuite","value":"TestWorkspaces"},{"name":"host","value":"fv-az1796-885"},{"name":"thread","value":"2090-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.workspaces_test"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":8,"skipped":0,"passed":0,"unknown":0,"total":8},"items":[{"uid":"65a3d967fc3e7aad","reportUrl":"https://nirtal85.github.io/Selenium-Python-Example/679//#testresult/65a3d967fc3e7aad","status":"broken","statusDetails":"FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/src/resources/tests_data.json'","time":{"start":1749434419020,"stop":1749434419020,"duration":0}},{"uid":"53038dcf429732ff","reportUrl":"https://nirtal85.github.io/Selenium-Python-Example/678//#testresult/53038dcf429732ff","status":"broken","statusDetails":"FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/src/resources/tests_data.json'","time":{"start":1749348193394,"stop":1749348193394,"duration":0}},{"uid":"4902fad34a8de933","reportUrl":"https://nirtal85.github.io/Selenium-Python-Example/677//#testresult/4902fad34a8de933","status":"broken","statusDetails":"FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/src/resources/tests_data.json'","time":{"start":1749261150625,"stop":1749261150625,"duration":0}},{"uid":"176f05ec52d7b831","reportUrl":"https://nirtal85.github.io/Selenium-Python-Example/676//#testresult/176f05ec52d7b831","status":"broken","statusDetails":"FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/src/resources/tests_data.json'","time":{"start":1749174780112,"stop":1749174780112,"duration":0}},{"uid":"ff80f77e74ab8af6","reportUrl":"https://nirtal85.github.io/Selenium-Python-Example/675//#testresult/ff80f77e74ab8af6","status":"broken","statusDetails":"FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/src/resources/tests_data.json'","time":{"start":1749088429701,"stop":1749088429701,"duration":0}},{"uid":"4ef2ec44afdccf28","reportUrl":"https://nirtal85.github.io/Selenium-Python-Example/674//#testresult/4ef2ec44afdccf28","status":"broken","statusDetails":"FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/src/resources/tests_data.json'","time":{"start":1749002098751,"stop":1749002098751,"duration":0}},{"uid":"3edc84b78eb7150d","reportUrl":"https://nirtal85.github.io/Selenium-Python-Example/673//#testresult/3edc84b78eb7150d","status":"broken","statusDetails":"FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/src/resources/tests_data.json'","time":{"start":1748915705112,"stop":1748915705112,"duration":0}}]},"tags":["run(order=1)"]},"source":"17e0830812a5235d.json","parameterValues":[]}