{"uid":"cd288bda97f2d14","name":"Login with invalid credentials test","fullName":"tests.login_test.TestLogin#test_invalid_login","historyId":"d8696551571014a71a874c85cadaf3fe","time":{"start":1706404400413,"stop":1706404410684,"duration":10271},"description":"invalid login","descriptionHtml":"<p>invalid login</p>\n","status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x55f3eb069f83 <unknown>\n#1 0x55f3ead22cf7 <unknown>\n#2 0x55f3ead7299e <unknown>\n#3 0x55f3ead72aa1 <unknown>\n#4 0x55f3eadbdd64 <unknown>\n#5 0x55f3ead9c0dd <unknown>\n#6 0x55f3eadbb006 <unknown>\n#7 0x55f3ead9be53 <unknown>\n#8 0x55f3ead63dd4 <unknown>\n#9 0x55f3ead651de <unknown>\n#10 0x55f3eb02e531 <unknown>\n#11 0x55f3eb032455 <unknown>\n#12 0x55f3eb01af55 <unknown>\n#13 0x55f3eb0330ef <unknown>\n#14 0x55f3eaffe99f <unknown>\n#15 0x55f3eb057008 <unknown>\n#16 0x55f3eb0571d7 <unknown>\n#17 0x55f3eb069124 <unknown>\n#18 0x7fdf3ca94ac3 <unknown>","statusTrace":"self = <tests.login_test.TestLogin object at 0x7f164fff8bc0>\nemail = 'nirt236@gmail.com', password = '123456'\ndata = Data(forgot_password=ForgotPassword(error_message=\"We can't find a user with that e-mail address.\", success_message='A...iteria', non_existing_project='Non Existing', project_name='test project', project_type='quiz', template_type='Blank'))\n\n    @allure.description(\"invalid login\")\n    @allure.title(\"Login with invalid credentials test\")\n    @pytest.mark.parametrize(\"email, password\", users)\n    @pytest.mark.run(order=3)\n    def test_invalid_login(self, email: str, password: str, data: Data):\n>       self.about_page.click_login_link()\n\ntests/login_test.py:26: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/about_page.py:20: in click_login_link\n    self.click(self.LOGIN_LINK)\npages/base_page.py:60: in click\n    el: WebElement = self.wait.until(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"b45889163cde9c9d6d17c6f57e9af3ca\")>\nmethod = <function element_to_be_clickable.<locals>._predicate at 0x7f164fe9d6c0>\nmessage = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       #0 0x55f3eb069f83 <unknown>\nE       #1 0x55f3ead22cf7 <unknown>\nE       #2 0x55f3ead7299e <unknown>\nE       #3 0x55f3ead72aa1 <unknown>\nE       #4 0x55f3eadbdd64 <unknown>\nE       #5 0x55f3ead9c0dd <unknown>\nE       #6 0x55f3eadbb006 <unknown>\nE       #7 0x55f3ead9be53 <unknown>\nE       #8 0x55f3ead63dd4 <unknown>\nE       #9 0x55f3ead651de <unknown>\nE       #10 0x55f3eb02e531 <unknown>\nE       #11 0x55f3eb032455 <unknown>\nE       #12 0x55f3eb01af55 <unknown>\nE       #13 0x55f3eb0330ef <unknown>\nE       #14 0x55f3eaffe99f <unknown>\nE       #15 0x55f3eb057008 <unknown>\nE       #16 0x55f3eb0571d7 <unknown>\nE       #17 0x55f3eb069124 <unknown>\nE       #18 0x7fdf3ca94ac3 <unknown>\n\n.venv/lib/python3.12/site-packages/selenium/webdriver/support/wait.py:105: TimeoutException","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_verify_url","time":{"start":1706404368291,"stop":1706404368291,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"base_url","time":{"start":1706404368291,"stop":1706404368291,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"data","time":{"start":1706404368291,"stop":1706404368292,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"description":"invalid login","status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x55f3eb069f83 <unknown>\n#1 0x55f3ead22cf7 <unknown>\n#2 0x55f3ead7299e <unknown>\n#3 0x55f3ead72aa1 <unknown>\n#4 0x55f3eadbdd64 <unknown>\n#5 0x55f3ead9c0dd <unknown>\n#6 0x55f3eadbb006 <unknown>\n#7 0x55f3ead9be53 <unknown>\n#8 0x55f3ead63dd4 <unknown>\n#9 0x55f3ead651de <unknown>\n#10 0x55f3eb02e531 <unknown>\n#11 0x55f3eb032455 <unknown>\n#12 0x55f3eb01af55 <unknown>\n#13 0x55f3eb0330ef <unknown>\n#14 0x55f3eaffe99f <unknown>\n#15 0x55f3eb057008 <unknown>\n#16 0x55f3eb0571d7 <unknown>\n#17 0x55f3eb069124 <unknown>\n#18 0x7fdf3ca94ac3 <unknown>","statusTrace":"self = <tests.login_test.TestLogin object at 0x7f164fff8bc0>\nemail = 'nirt236@gmail.com', password = '123456'\ndata = Data(forgot_password=ForgotPassword(error_message=\"We can't find a user with that e-mail address.\", success_message='A...iteria', non_existing_project='Non Existing', project_name='test project', project_type='quiz', template_type='Blank'))\n\n    @allure.description(\"invalid login\")\n    @allure.title(\"Login with invalid credentials test\")\n    @pytest.mark.parametrize(\"email, password\", users)\n    @pytest.mark.run(order=3)\n    def test_invalid_login(self, email: str, password: str, data: Data):\n>       self.about_page.click_login_link()\n\ntests/login_test.py:26: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/about_page.py:20: in click_login_link\n    self.click(self.LOGIN_LINK)\npages/base_page.py:60: in click\n    el: WebElement = self.wait.until(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"b45889163cde9c9d6d17c6f57e9af3ca\")>\nmethod = <function element_to_be_clickable.<locals>._predicate at 0x7f164fe9d6c0>\nmessage = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       #0 0x55f3eb069f83 <unknown>\nE       #1 0x55f3ead22cf7 <unknown>\nE       #2 0x55f3ead7299e <unknown>\nE       #3 0x55f3ead72aa1 <unknown>\nE       #4 0x55f3eadbdd64 <unknown>\nE       #5 0x55f3ead9c0dd <unknown>\nE       #6 0x55f3eadbb006 <unknown>\nE       #7 0x55f3ead9be53 <unknown>\nE       #8 0x55f3ead63dd4 <unknown>\nE       #9 0x55f3ead651de <unknown>\nE       #10 0x55f3eb02e531 <unknown>\nE       #11 0x55f3eb032455 <unknown>\nE       #12 0x55f3eb01af55 <unknown>\nE       #13 0x55f3eb0330ef <unknown>\nE       #14 0x55f3eaffe99f <unknown>\nE       #15 0x55f3eb057008 <unknown>\nE       #16 0x55f3eb0571d7 <unknown>\nE       #17 0x55f3eb069124 <unknown>\nE       #18 0x7fdf3ca94ac3 <unknown>\n\n.venv/lib/python3.12/site-packages/selenium/webdriver/support/wait.py:105: TimeoutException","steps":[{"name":"Click Login link","time":{"start":1706404400413,"stop":1706404410684,"duration":10271},"status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x55f3eb069f83 <unknown>\n#1 0x55f3ead22cf7 <unknown>\n#2 0x55f3ead7299e <unknown>\n#3 0x55f3ead72aa1 <unknown>\n#4 0x55f3eadbdd64 <unknown>\n#5 0x55f3ead9c0dd <unknown>\n#6 0x55f3eadbb006 <unknown>\n#7 0x55f3ead9be53 <unknown>\n#8 0x55f3ead63dd4 <unknown>\n#9 0x55f3ead651de <unknown>\n#10 0x55f3eb02e531 <unknown>\n#11 0x55f3eb032455 <unknown>\n#12 0x55f3eb01af55 <unknown>\n#13 0x55f3eb0330ef <unknown>\n#14 0x55f3eaffe99f <unknown>\n#15 0x55f3eb057008 <unknown>\n#16 0x55f3eb0571d7 <unknown>\n#17 0x55f3eb069124 <unknown>\n#18 0x7fdf3ca94ac3 <unknown>\n\n","statusTrace":"  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/.venv/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/pages/about_page.py\", line 20, in click_login_link\n    self.click(self.LOGIN_LINK)\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/pages/base_page.py\", line 60, in click\n    el: WebElement = self.wait.until(\n                     ^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/.venv/lib/python3.12/site-packages/selenium/webdriver/support/wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[{"uid":"7b3bbfd76745127e","name":"public ip address","source":"7b3bbfd76745127e.txt","type":"text/plain","size":11},{"uid":"92cb7db1dcd5a791","name":"Cookies","source":"92cb7db1dcd5a791.json","type":"application/json","size":3872},{"uid":"a436615dfdbd434f","name":"Session Storage","source":"a436615dfdbd434f.json","type":"application/json","size":359},{"uid":"479c062e266c7dfe","name":"Local Storage","source":"479c062e266c7dfe.json","type":"application/json","size":208},{"uid":"b353a4910f75b625","name":"Console Logs","source":"b353a4910f75b625.json","type":"application/json","size":2},{"uid":"30a6d1c8f144e7f7","name":"Full Page Screenshot","source":"30a6d1c8f144e7f7.png","type":"image/png","size":5702497},{"uid":"db45dcd1228c45c4","name":"URL","source":"db45dcd1228c45c4.uri","type":"text/uri-list","size":23},{"uid":"c22433f26ddd02fc","name":"Network Logs","source":"c22433f26ddd02fc.json","type":"application/json","size":23280}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":1,"attachmentsCount":8,"hasContent":true,"attachmentStep":false},"afterStages":[],"labels":[{"name":"epic","value":"Security"},{"name":"severity","value":"blocker"},{"name":"feature","value":"Login"},{"name":"tag","value":"run(order=3)"},{"name":"tag","value":"security"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"login_test"},{"name":"subSuite","value":"TestLogin"},{"name":"host","value":"fv-az1536-984"},{"name":"thread","value":"2337-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.login_test"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"email","value":"'nirt236@gmail.com'"},{"name":"password","value":"'123456'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"blocker","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":["run(order=3)","security"]},"source":"cd288bda97f2d14.json","parameterValues":["'nirt236@gmail.com'","'123456'"]}