{"uid":"139b3353da556026","name":"Login with invalid credentials test","fullName":"tests.login_test.TestLogin#test_invalid_login","historyId":"d8696551571014a71a874c85cadaf3fe","time":{"start":1710724184879,"stop":1710724195140,"duration":10261},"description":"invalid login","descriptionHtml":"<p>invalid login</p>\n","status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x6409f574aec3 <unknown>\n#1 0x6409f5442ce6 <unknown>\n#2 0x6409f548de48 <unknown>\n#3 0x6409f548df01 <unknown>\n#4 0x6409f54d13f4 <unknown>\n#5 0x6409f54afedd <unknown>\n#6 0x6409f54ce899 <unknown>\n#7 0x6409f54afc53 <unknown>\n#8 0x6409f5480db3 <unknown>\n#9 0x6409f548177e <unknown>\n#10 0x6409f57107fb <unknown>\n#11 0x6409f5714815 <unknown>\n#12 0x6409f56fe111 <unknown>\n#13 0x6409f57153a2 <unknown>\n#14 0x6409f56e21ef <unknown>\n#15 0x6409f57394b8 <unknown>\n#16 0x6409f57396b3 <unknown>\n#17 0x6409f574a074 <unknown>\n#18 0x7d322b094ac3 <unknown>","statusTrace":"self = <tests.login_test.TestLogin object at 0x7e2483a32990>\nemail = 'nirt236@gmail.com', password = '123456'\ndata = Data(forgot_password=ForgotPassword(error_message=\"We can't find a user with that e-mail address.\", success_message='A...ct='Non Existing', page_title='My Workspace', project_name='test project', project_type='quiz', template_type='Blank'))\n\n    @allure.description(\"invalid login\")\n    @allure.title(\"Login with invalid credentials test\")\n    @pytest.mark.parametrize(\"email, password\", users)\n    @pytest.mark.run(order=3)\n    def test_invalid_login(self, email: str, password: str, data: Data):\n>       self.about_page.click_login_link()\n\ntests/login_test.py:26: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/about_page.py:20: in click_login_link\n    self.click(self.LOGIN_LINK)\npages/base_page.py:60: in click\n    el: WebElement = self.wait.until(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"525da0db7d095ff36131d312a071bda5\")>\nmethod = <function element_to_be_clickable.<locals>._predicate at 0x7e2483135620>\nmessage = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       #0 0x6409f574aec3 <unknown>\nE       #1 0x6409f5442ce6 <unknown>\nE       #2 0x6409f548de48 <unknown>\nE       #3 0x6409f548df01 <unknown>\nE       #4 0x6409f54d13f4 <unknown>\nE       #5 0x6409f54afedd <unknown>\nE       #6 0x6409f54ce899 <unknown>\nE       #7 0x6409f54afc53 <unknown>\nE       #8 0x6409f5480db3 <unknown>\nE       #9 0x6409f548177e <unknown>\nE       #10 0x6409f57107fb <unknown>\nE       #11 0x6409f5714815 <unknown>\nE       #12 0x6409f56fe111 <unknown>\nE       #13 0x6409f57153a2 <unknown>\nE       #14 0x6409f56e21ef <unknown>\nE       #15 0x6409f57394b8 <unknown>\nE       #16 0x6409f57396b3 <unknown>\nE       #17 0x6409f574a074 <unknown>\nE       #18 0x7d322b094ac3 <unknown>\n\n.venv/lib/python3.12/site-packages/selenium/webdriver/support/wait.py:105: TimeoutException","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"base_url","time":{"start":1710724152704,"stop":1710724152704,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"_verify_url","time":{"start":1710724152705,"stop":1710724152705,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"data","time":{"start":1710724152705,"stop":1710724152706,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"description":"invalid login","status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x6409f574aec3 <unknown>\n#1 0x6409f5442ce6 <unknown>\n#2 0x6409f548de48 <unknown>\n#3 0x6409f548df01 <unknown>\n#4 0x6409f54d13f4 <unknown>\n#5 0x6409f54afedd <unknown>\n#6 0x6409f54ce899 <unknown>\n#7 0x6409f54afc53 <unknown>\n#8 0x6409f5480db3 <unknown>\n#9 0x6409f548177e <unknown>\n#10 0x6409f57107fb <unknown>\n#11 0x6409f5714815 <unknown>\n#12 0x6409f56fe111 <unknown>\n#13 0x6409f57153a2 <unknown>\n#14 0x6409f56e21ef <unknown>\n#15 0x6409f57394b8 <unknown>\n#16 0x6409f57396b3 <unknown>\n#17 0x6409f574a074 <unknown>\n#18 0x7d322b094ac3 <unknown>","statusTrace":"self = <tests.login_test.TestLogin object at 0x7e2483a32990>\nemail = 'nirt236@gmail.com', password = '123456'\ndata = Data(forgot_password=ForgotPassword(error_message=\"We can't find a user with that e-mail address.\", success_message='A...ct='Non Existing', page_title='My Workspace', project_name='test project', project_type='quiz', template_type='Blank'))\n\n    @allure.description(\"invalid login\")\n    @allure.title(\"Login with invalid credentials test\")\n    @pytest.mark.parametrize(\"email, password\", users)\n    @pytest.mark.run(order=3)\n    def test_invalid_login(self, email: str, password: str, data: Data):\n>       self.about_page.click_login_link()\n\ntests/login_test.py:26: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/about_page.py:20: in click_login_link\n    self.click(self.LOGIN_LINK)\npages/base_page.py:60: in click\n    el: WebElement = self.wait.until(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"525da0db7d095ff36131d312a071bda5\")>\nmethod = <function element_to_be_clickable.<locals>._predicate at 0x7e2483135620>\nmessage = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       #0 0x6409f574aec3 <unknown>\nE       #1 0x6409f5442ce6 <unknown>\nE       #2 0x6409f548de48 <unknown>\nE       #3 0x6409f548df01 <unknown>\nE       #4 0x6409f54d13f4 <unknown>\nE       #5 0x6409f54afedd <unknown>\nE       #6 0x6409f54ce899 <unknown>\nE       #7 0x6409f54afc53 <unknown>\nE       #8 0x6409f5480db3 <unknown>\nE       #9 0x6409f548177e <unknown>\nE       #10 0x6409f57107fb <unknown>\nE       #11 0x6409f5714815 <unknown>\nE       #12 0x6409f56fe111 <unknown>\nE       #13 0x6409f57153a2 <unknown>\nE       #14 0x6409f56e21ef <unknown>\nE       #15 0x6409f57394b8 <unknown>\nE       #16 0x6409f57396b3 <unknown>\nE       #17 0x6409f574a074 <unknown>\nE       #18 0x7d322b094ac3 <unknown>\n\n.venv/lib/python3.12/site-packages/selenium/webdriver/support/wait.py:105: TimeoutException","steps":[{"name":"Click Login link","time":{"start":1710724184879,"stop":1710724195139,"duration":10260},"status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x6409f574aec3 <unknown>\n#1 0x6409f5442ce6 <unknown>\n#2 0x6409f548de48 <unknown>\n#3 0x6409f548df01 <unknown>\n#4 0x6409f54d13f4 <unknown>\n#5 0x6409f54afedd <unknown>\n#6 0x6409f54ce899 <unknown>\n#7 0x6409f54afc53 <unknown>\n#8 0x6409f5480db3 <unknown>\n#9 0x6409f548177e <unknown>\n#10 0x6409f57107fb <unknown>\n#11 0x6409f5714815 <unknown>\n#12 0x6409f56fe111 <unknown>\n#13 0x6409f57153a2 <unknown>\n#14 0x6409f56e21ef <unknown>\n#15 0x6409f57394b8 <unknown>\n#16 0x6409f57396b3 <unknown>\n#17 0x6409f574a074 <unknown>\n#18 0x7d322b094ac3 <unknown>\n\n","statusTrace":"  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/.venv/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/pages/about_page.py\", line 20, in click_login_link\n    self.click(self.LOGIN_LINK)\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/pages/base_page.py\", line 60, in click\n    el: WebElement = self.wait.until(\n                     ^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/Selenium-Python-Example/Selenium-Python-Example/.venv/lib/python3.12/site-packages/selenium/webdriver/support/wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[{"uid":"5a4ad7a4d843a245","name":"public ip address","source":"5a4ad7a4d843a245.txt","type":"text/plain","size":14},{"uid":"5cf1546f24f9d2ef","name":"Cookies","source":"5cf1546f24f9d2ef.json","type":"application/json","size":3096},{"uid":"9afdb59e03e4cea4","name":"Session Storage","source":"9afdb59e03e4cea4.json","type":"application/json","size":359},{"uid":"481eb95bd1ec03fe","name":"Local Storage","source":"481eb95bd1ec03fe.json","type":"application/json","size":208},{"uid":"28b53788942d1f47","name":"Console Logs","source":"28b53788942d1f47.json","type":"application/json","size":653},{"uid":"8b56c53e10c6586a","name":"Full Page Screenshot","source":"8b56c53e10c6586a.png","type":"image/png","size":6185304},{"uid":"abb217d800258f88","name":"URL","source":"abb217d800258f88.uri","type":"text/uri-list","size":23},{"uid":"8badd9aec9847784","name":"Network Logs","source":"8badd9aec9847784.json","type":"application/json","size":23197}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":1,"attachmentsCount":8,"hasContent":true,"attachmentStep":false},"afterStages":[],"labels":[{"name":"feature","value":"Login"},{"name":"epic","value":"Security"},{"name":"severity","value":"blocker"},{"name":"tag","value":"run(order=3)"},{"name":"tag","value":"security"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"login_test"},{"name":"subSuite","value":"TestLogin"},{"name":"host","value":"fv-az1240-72"},{"name":"thread","value":"2417-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.login_test"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"email","value":"'nirt236@gmail.com'"},{"name":"password","value":"'123456'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"blocker","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":["run(order=3)","security"]},"source":"139b3353da556026.json","parameterValues":["'nirt236@gmail.com'","'123456'"]}